version: '3.3'
services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:${RABBIT_MQ_VERSION}-alpine
        ports:
        - 5673:5672
        - 15673:15672
        expose:
            - 5672
    redis:
        container_name: redis
        image: redis:${REDIS_VERSION}-alpine
        ports:
            - 6380:6379
        expose:
            - 6379
