version: '3.7'
x-celery-worker:
  &celery-worker
  image: celery_worker
  command: [ 'celery', '-A', 'tasks', 'worker', '--loglevel', 'info', '--queues','${WORKER_QUEUE}', '-n', '${WORKER_NAME}' ]
  depends_on:
    - rabbitmq
    - redis
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.9
    ports:
      - 5673:5672
      - 15673:15672
    expose:
      - 5672
    healthcheck:
      test: ["CMD", 'rabbitmq-diagnostics', '-q', 'ping', '&&', 'rabbitmq-diagnostics', '-q', 'status', '&&', 'nc', '-z', 'localhost', '5672']
      interval: 30s
      timeout: 30s
      retries: 3
  redis:
    container_name: redis
    image: redis:6.0.10-alpine
    ports:
      - 6380:6379
    expose:
      - 6379
  default-worker:
    <<: *celery-worker
    container_name: default-worker
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:5672//
      - CELERY_RESULTS_BACKEND=redis://redis:6379/0
      - WORKER_QUEUE=default
      - WORKER_NAME=default
  gpu-worker:
    <<: *celery-worker
    container_name: gpu-worker
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:5672//
      - CELERY_RESULTS_BACKEND=redis://redis:6379/0
      - WORKER_QUEUE=gpu
      - WORKER_NAME=gpu