apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: broker-scaler-auth
  namespace: celery-autoscale
spec:
  secretTargetRef:
    - parameter: host
      name: celery-broker-secret
      key: admin-host