apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-broker
  namespace: celery-autoscale
  labels:
    app: celery-broker
spec:
  replicas: 1
  template:
    metadata:
      name: celery-broker
      labels:
        app: celery-broker
    spec:
      containers:
        - name: celery-broker
          image: rabbitmq:3.8.16-management-alpine
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: celery-broker

---

apiVersion: v1
kind: Service
metadata:
  name: celery-broker
  namespace: celery-autoscale
spec:
  type: NodePort
  selector:
    app: celery-broker
  ports:
    - name: port
      protocol: TCP
      port: 5672
      nodePort: 32672
    - name: managment
      protocol: TCP
      port: 15672
      nodePort: 32673

---

apiVersion: v1
kind: Secret
metadata:
  name: celery-broker-secret
  namespace: celery-autoscale
data:
  user-name: Z3Vlc3Q= # guest
  user-password: Z3Vlc3Q= # guest
  amqp-url: YW1xcDovL2d1ZXN0Omd1ZXN0QGNlbGVyeS1icm9rZXI6NTY3Mi8v # amqp://guest:guest@celery-broker:5672//
  admin-host: aHR0cDovL2d1ZXN0Omd1ZXN0QGNlbGVyeS1icm9rZXIuY2VsZXJ5LWF1dG9zY2FsZS5zdmMuY2x1c3Rlci5sb2NhbDoxNTY3Mi8= # http://guest:guest@celery-broker.celery-autoscale.svc.cluster.local:15672/
