apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-results
  namespace: celery-autoscale
  labels:
    app: celery-results
spec:
  replicas: 1
  template:
    metadata:
      name: celery-results
      labels:
        app: celery-results
    spec:
      containers:
        - name: celery-results
          image: redis:6.0.10-alpine
          imagePullPolicy: Always
          ports:
            - name: client
              containerPort: 6379
            - name: gossip
              containerPort: 16379
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 3
          livenessProbe:
            tcpSocket:
              port: client # named port
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 5
            successThreshold: 1
      restartPolicy: Always
  selector:
    matchLabels:
      app: celery-results

---
apiVersion: v1
kind: Service
metadata:
  name: celery-results
  namespace: celery-autoscale
spec:
  type: NodePort
  selector:
    app: celery-results
  ports:
    - protocol: TCP
      port: 6379
      nodePort: 32379
