apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-worker
  namespace: celery-autoscale
  labels:
    app: default-worker
spec:
  replicas: 0
  template:
    metadata:
      name: default-worker
      labels:
        app: default-worker
    spec:
      containers:
        - name: default-worker
          image: celery-worker
          imagePullPolicy: Never
          command: ['sh', '-c']
          args: ['celery -A tasks worker --loglevel INFO --queues $(WORKER_QUEUE) -n $(WORKER_PREFIX)-${HOSTNAME} -c 1']
          readinessProbe:
            exec:
              command: ['sh', '-c', 'celery', '-A', 'tasks', 'inspect', 'ping', '-d', 'celery@$(WORKER_PREFIX)-${HOSTNAME}']
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 3
          livenessProbe:
            exec:
              command: ['sh', '-c', 'celery', '-A', 'tasks', 'inspect', 'ping', '-d', 'celery@$(WORKER_PREFIX)-${HOSTNAME}']
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 3
            failureThreshold: 5
            successThreshold: 1
          env:
          - name: CELERY_BROKER_URL
            value: amqp://celery-broker:5672//
          - name: CELERY_RESULTS_BACKEND
            value: redis://celery-results:6379/0
          - name: WORKER_QUEUE
            value: default
          - name: WORKER_PREFIX
            value: default-worker
      restartPolicy: Always
  selector:
    matchLabels:
      app: default-worker
