apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-worker-deployment
  labels:
    app: default-worker
spec:
  replicas: 1
  template:
    metadata:
      name: default-worker
      labels:
        app: default-worker
    spec:
      containers:
        - name: default-worker
          image: celery_worker
          imagePullPolicy: Never
          readinessProbe:
            exec:
              command: ['celery', '-A', 'tasks', 'inspect', 'ping', '-d', 'celery@$(WORKER_NAME)']
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 3
          livenessProbe:
            exec:
              command: [ 'celery', '-A', 'tasks', 'inspect', 'ping', '-d', 'celery@$(WORKER_NAME)' ]
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 3
            failureThreshold: 5
            successThreshold: 1
          env:
          - name: CELERY_BROKER_URL
            value: amqp://rabbitmq-service:5672//
          - name: CELERY_RESULTS_BACKEND
            value: redis://redis-service:6379/0
          - name: WORKER_QUEUE
            value: default
          - name: WORKER_NAME
            value: default-worker
      restartPolicy: Always
  selector:
    matchLabels:
      app: default-worker
