apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      name: rabbitmq
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.8.16-alpine
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: rabbitmq

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - name: port
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: managment
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: NodePort