apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: celey-autoscale-framework
build:
  local:
    useBuildkit: true
    push: false
  artifacts:
  - image: celery_worker
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '**/*.py'
          dest: .
deploy:
  kubectl:
    manifests:
    - deployment/kubernetes/celery-broker.yml
    - deployment/kubernetes/celery-results.yml
    - deployment/kubernetes/default-worker.yml
    - deployment/kubernetes/gpu-worker.yml
